export const bookGenres = [
  'Fiction',
  'Mystery',
  'Biography',
  'Business',
  'Thriller',
  'Romance',
  'Fantasy',
  'Adventure',
  'Science Fiction',
  'Dystopian',
  'Non-Fiction',
  "Children's Books",
  'Historical',
  'Horror',
]; // array of possible book genres -  because otherwise it would get wild
